# Generated by Django 3.1.2 on 2020-11-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eecs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='编号')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '毕业要求表',
                'verbose_name_plural': '毕业要求表',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': '用户-角色表', 'verbose_name_plural': '用户-角色表'},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eecs.role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('role', 'user')},
        ),
        migrations.CreateModel(
            name='Point2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='编号')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eecs.point1', verbose_name='所属毕业要求')),
            ],
            options={
                'verbose_name': '指标点分解表',
                'verbose_name_plural': '指标点分解表',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='专业名称')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='专业负责人')),
            ],
            options={
                'verbose_name': '专业表',
                'verbose_name_plural': '专业表',
            },
        ),
    ]
