# Generated by Django 3.1.2 on 2020-11-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eecs', '0002_auto_20201128_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='user',
            new_name='manager',
        ),
    ]
