# Generated by Django 3.1.2 on 2020-11-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eecs', '0004_point1_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point1',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eecs.major', verbose_name='专业'),
        ),
    ]
